
# Filepaths

TEMP_DIR = ".tmp/"
VECTOR_STORE = TEMP_DIR + "v-store/"
INPUT_FILE_PATH = TEMP_DIR + "input/"
OUTPUT_FILE_PATH = TEMP_DIR + "output/"
BUFFER_FILE_PATH = TEMP_DIR + "buffer/"
IMAGE_FILE_PATH = TEMP_DIR + "image/"

ALL_FILE_DIRS = [INPUT_FILE_PATH, OUTPUT_FILE_PATH, BUFFER_FILE_PATH, IMAGE_FILE_PATH]
