
# Filepaths

TEMP_DIR = ".tmp/"
VECTOR_STORE = TEMP_DIR + "v-store/"
INPUT_FILE_PATH = TEMP_DIR + "input/"
OUTPUT_FILE_PATH = TEMP_DIR + "output/"
EXTRACTED_FILE_PATH = TEMP_DIR + "extracted/"
INTERMEDIATE_FILE_PATH = TEMP_DIR + "inter/"

ALL_FILE_DIRS = [INPUT_FILE_PATH, OUTPUT_FILE_PATH, EXTRACTED_FILE_PATH, INTERMEDIATE_FILE_PATH]
