[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"  # Light background
secondaryBackgroundColor = "#f0f0f5"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8000
enableCORS = true